//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.MANDATORYSKIL), "CANDIDATE_DETAILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.CANDIDATE_DETAILS), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.OPTIONALSKIL), "CANDIDATE_DETAILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.CANDIDATE_DETAILS), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.INTERVIEWER), "MANDATORYSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.MANDATORYSKIL), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__OPTIONALSKI__IID__24927208", "INTERVIEWER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.INTERVIEWER), "OPTIONALSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.OPTIONALSKIL), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__MANDATORY__INTER__1CF15040", "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.Rating), "MANDATORYSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.MANDATORYSKIL), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__MANDATORYS__JRSS__1BFD2C07", "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.Rating), "MANDATORYSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.MANDATORYSKIL), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__OPTIONALS__INTER__239E4DCF", "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.Rating), "OPTIONALSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.OPTIONALSKIL), true)]
[assembly: EdmRelationshipAttribute("RegFormAngularNodeModel", "FK__OPTIONALSK__JRSS__22AA2996", "Rating", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(RegFormAN.Models.Rating), "OPTIONALSKILS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(RegFormAN.Models.OPTIONALSKIL), true)]

#endregion

namespace RegFormAN.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RegFormAngularNodeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RegFormAngularNodeEntities object using the connection string found in the 'RegFormAngularNodeEntities' section of the application configuration file.
        /// </summary>
        public RegFormAngularNodeEntities() : base("name=RegFormAngularNodeEntities", "RegFormAngularNodeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RegFormAngularNodeEntities object.
        /// </summary>
        public RegFormAngularNodeEntities(string connectionString) : base(connectionString, "RegFormAngularNodeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RegFormAngularNodeEntities object.
        /// </summary>
        public RegFormAngularNodeEntities(EntityConnection connection) : base(connection, "RegFormAngularNodeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CANDIDATE_DETAILS> CANDIDATE_DETAILS
        {
            get
            {
                if ((_CANDIDATE_DETAILS == null))
                {
                    _CANDIDATE_DETAILS = base.CreateObjectSet<CANDIDATE_DETAILS>("CANDIDATE_DETAILS");
                }
                return _CANDIDATE_DETAILS;
            }
        }
        private ObjectSet<CANDIDATE_DETAILS> _CANDIDATE_DETAILS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<INTERVIEWER> INTERVIEWERs
        {
            get
            {
                if ((_INTERVIEWERs == null))
                {
                    _INTERVIEWERs = base.CreateObjectSet<INTERVIEWER>("INTERVIEWERs");
                }
                return _INTERVIEWERs;
            }
        }
        private ObjectSet<INTERVIEWER> _INTERVIEWERs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MANDATORYSKIL> MANDATORYSKILS
        {
            get
            {
                if ((_MANDATORYSKILS == null))
                {
                    _MANDATORYSKILS = base.CreateObjectSet<MANDATORYSKIL>("MANDATORYSKILS");
                }
                return _MANDATORYSKILS;
            }
        }
        private ObjectSet<MANDATORYSKIL> _MANDATORYSKILS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OPTIONALSKIL> OPTIONALSKILS
        {
            get
            {
                if ((_OPTIONALSKILS == null))
                {
                    _OPTIONALSKILS = base.CreateObjectSet<OPTIONALSKIL>("OPTIONALSKILS");
                }
                return _OPTIONALSKILS;
            }
        }
        private ObjectSet<OPTIONALSKIL> _OPTIONALSKILS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rating> Ratings
        {
            get
            {
                if ((_Ratings == null))
                {
                    _Ratings = base.CreateObjectSet<Rating>("Ratings");
                }
                return _Ratings;
            }
        }
        private ObjectSet<Rating> _Ratings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CANDIDATE_DETAILS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCANDIDATE_DETAILS(CANDIDATE_DETAILS cANDIDATE_DETAILS)
        {
            base.AddObject("CANDIDATE_DETAILS", cANDIDATE_DETAILS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the INTERVIEWERs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToINTERVIEWERs(INTERVIEWER iNTERVIEWER)
        {
            base.AddObject("INTERVIEWERs", iNTERVIEWER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MANDATORYSKILS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMANDATORYSKILS(MANDATORYSKIL mANDATORYSKIL)
        {
            base.AddObject("MANDATORYSKILS", mANDATORYSKIL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OPTIONALSKILS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOPTIONALSKILS(OPTIONALSKIL oPTIONALSKIL)
        {
            base.AddObject("OPTIONALSKILS", oPTIONALSKIL);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ratings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRatings(Rating rating)
        {
            base.AddObject("Ratings", rating);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RegFormAngularNodeModel", Name="CANDIDATE_DETAILS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CANDIDATE_DETAILS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CANDIDATE_DETAILS object.
        /// </summary>
        /// <param name="cID">Initial value of the CID property.</param>
        public static CANDIDATE_DETAILS CreateCANDIDATE_DETAILS(global::System.Int32 cID)
        {
            CANDIDATE_DETAILS cANDIDATE_DETAILS = new CANDIDATE_DETAILS();
            cANDIDATE_DETAILS.CID = cID;
            return cANDIDATE_DETAILS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Int32 _CID;
        partial void OnCIDChanging(global::System.Int32 value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CANDIDATE_NAME
        {
            get
            {
                return _CANDIDATE_NAME;
            }
            set
            {
                OnCANDIDATE_NAMEChanging(value);
                ReportPropertyChanging("CANDIDATE_NAME");
                _CANDIDATE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CANDIDATE_NAME");
                OnCANDIDATE_NAMEChanged();
            }
        }
        private global::System.String _CANDIDATE_NAME;
        partial void OnCANDIDATE_NAMEChanging(global::System.String value);
        partial void OnCANDIDATE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PROJECT
        {
            get
            {
                return _PROJECT;
            }
            set
            {
                OnPROJECTChanging(value);
                ReportPropertyChanging("PROJECT");
                _PROJECT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PROJECT");
                OnPROJECTChanged();
            }
        }
        private global::System.String _PROJECT;
        partial void OnPROJECTChanging(global::System.String value);
        partial void OnPROJECTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRACTICE_AREA
        {
            get
            {
                return _PRACTICE_AREA;
            }
            set
            {
                OnPRACTICE_AREAChanging(value);
                ReportPropertyChanging("PRACTICE_AREA");
                _PRACTICE_AREA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRACTICE_AREA");
                OnPRACTICE_AREAChanged();
            }
        }
        private global::System.String _PRACTICE_AREA;
        partial void OnPRACTICE_AREAChanging(global::System.String value);
        partial void OnPRACTICE_AREAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Requester
        {
            get
            {
                return _Requester;
            }
            set
            {
                OnRequesterChanging(value);
                ReportPropertyChanging("Requester");
                _Requester = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Requester");
                OnRequesterChanged();
            }
        }
        private global::System.String _Requester;
        partial void OnRequesterChanging(global::System.String value);
        partial void OnRequesterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MID
        {
            get
            {
                return _MID;
            }
            set
            {
                OnMIDChanging(value);
                ReportPropertyChanging("MID");
                _MID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MID");
                OnMIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MID;
        partial void OnMIDChanging(Nullable<global::System.Int32> value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OID
        {
            get
            {
                return _OID;
            }
            set
            {
                OnOIDChanging(value);
                ReportPropertyChanging("OID");
                _OID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OID");
                OnOIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OID;
        partial void OnOIDChanging(Nullable<global::System.Int32> value);
        partial void OnOIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS")]
        public MANDATORYSKIL MANDATORYSKIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MANDATORYSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MANDATORYSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MANDATORYSKIL> MANDATORYSKILReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MANDATORYSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MANDATORYSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "MANDATORYSKILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS")]
        public OPTIONALSKIL OPTIONALSKIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OPTIONALSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OPTIONALSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OPTIONALSKIL> OPTIONALSKILReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OPTIONALSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OPTIONALSKIL>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "OPTIONALSKILS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RegFormAngularNodeModel", Name="INTERVIEWER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class INTERVIEWER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new INTERVIEWER object.
        /// </summary>
        /// <param name="iID">Initial value of the IID property.</param>
        public static INTERVIEWER CreateINTERVIEWER(global::System.Int32 iID)
        {
            INTERVIEWER iNTERVIEWER = new INTERVIEWER();
            iNTERVIEWER.IID = iID;
            return iNTERVIEWER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IID
        {
            get
            {
                return _IID;
            }
            set
            {
                if (_IID != value)
                {
                    OnIIDChanging(value);
                    ReportPropertyChanging("IID");
                    _IID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IID");
                    OnIIDChanged();
                }
            }
        }
        private global::System.Int32 _IID;
        partial void OnIIDChanging(global::System.Int32 value);
        partial void OnIIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INAME
        {
            get
            {
                return _INAME;
            }
            set
            {
                OnINAMEChanging(value);
                ReportPropertyChanging("INAME");
                _INAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INAME");
                OnINAMEChanged();
            }
        }
        private global::System.String _INAME;
        partial void OnINAMEChanging(global::System.String value);
        partial void OnINAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SIGN
        {
            get
            {
                return _SIGN;
            }
            set
            {
                OnSIGNChanging(value);
                ReportPropertyChanging("SIGN");
                _SIGN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SIGN");
                OnSIGNChanged();
            }
        }
        private global::System.String _SIGN;
        partial void OnSIGNChanging(global::System.String value);
        partial void OnSIGNChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORYSK__IID__1DE57479", "MANDATORYSKILS")]
        public EntityCollection<MANDATORYSKIL> MANDATORYSKILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "MANDATORYSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "MANDATORYSKILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALSKI__IID__24927208", "OPTIONALSKILS")]
        public EntityCollection<OPTIONALSKIL> OPTIONALSKILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "OPTIONALSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "OPTIONALSKILS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RegFormAngularNodeModel", Name="MANDATORYSKIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MANDATORYSKIL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MANDATORYSKIL object.
        /// </summary>
        /// <param name="mID">Initial value of the MID property.</param>
        public static MANDATORYSKIL CreateMANDATORYSKIL(global::System.Int32 mID)
        {
            MANDATORYSKIL mANDATORYSKIL = new MANDATORYSKIL();
            mANDATORYSKIL.MID = mID;
            return mANDATORYSKIL;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Int32 _MID;
        partial void OnMIDChanging(global::System.Int32 value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SKILL
        {
            get
            {
                return _SKILL;
            }
            set
            {
                OnSKILLChanging(value);
                ReportPropertyChanging("SKILL");
                _SKILL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SKILL");
                OnSKILLChanged();
            }
        }
        private global::System.String _SKILL;
        partial void OnSKILLChanging(global::System.String value);
        partial void OnSKILLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JRSS
        {
            get
            {
                return _JRSS;
            }
            set
            {
                OnJRSSChanging(value);
                ReportPropertyChanging("JRSS");
                _JRSS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JRSS");
                OnJRSSChanged();
            }
        }
        private Nullable<global::System.Int32> _JRSS;
        partial void OnJRSSChanging(Nullable<global::System.Int32> value);
        partial void OnJRSSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> INTERVIEWERRATING
        {
            get
            {
                return _INTERVIEWERRATING;
            }
            set
            {
                OnINTERVIEWERRATINGChanging(value);
                ReportPropertyChanging("INTERVIEWERRATING");
                _INTERVIEWERRATING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INTERVIEWERRATING");
                OnINTERVIEWERRATINGChanged();
            }
        }
        private Nullable<global::System.Int32> _INTERVIEWERRATING;
        partial void OnINTERVIEWERRATINGChanging(Nullable<global::System.Int32> value);
        partial void OnINTERVIEWERRATINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IID
        {
            get
            {
                return _IID;
            }
            set
            {
                OnIIDChanging(value);
                ReportPropertyChanging("IID");
                _IID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IID");
                OnIIDChanged();
            }
        }
        private Nullable<global::System.Int32> _IID;
        partial void OnIIDChanging(Nullable<global::System.Int32> value);
        partial void OnIIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__MID__267ABA7A", "CANDIDATE_DETAILS")]
        public EntityCollection<CANDIDATE_DETAILS> CANDIDATE_DETAILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CANDIDATE_DETAILS>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "CANDIDATE_DETAILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CANDIDATE_DETAILS>("RegFormAngularNodeModel.FK__CANDIDATE_D__MID__267ABA7A", "CANDIDATE_DETAILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER")]
        public INTERVIEWER INTERVIEWER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INTERVIEWER> INTERVIEWERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__MANDATORYSK__IID__1DE57479", "INTERVIEWER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORY__INTER__1CF15040", "Rating")]
        public Rating Rating
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "Rating").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "Rating").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rating> RatingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "Rating", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORYS__JRSS__1BFD2C07", "Rating")]
        public Rating Rating1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "Rating").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "Rating").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rating> Rating1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rating>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "Rating", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RegFormAngularNodeModel", Name="OPTIONALSKIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OPTIONALSKIL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OPTIONALSKIL object.
        /// </summary>
        /// <param name="oID">Initial value of the OID property.</param>
        public static OPTIONALSKIL CreateOPTIONALSKIL(global::System.Int32 oID)
        {
            OPTIONALSKIL oPTIONALSKIL = new OPTIONALSKIL();
            oPTIONALSKIL.OID = oID;
            return oPTIONALSKIL;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OID
        {
            get
            {
                return _OID;
            }
            set
            {
                if (_OID != value)
                {
                    OnOIDChanging(value);
                    ReportPropertyChanging("OID");
                    _OID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OID");
                    OnOIDChanged();
                }
            }
        }
        private global::System.Int32 _OID;
        partial void OnOIDChanging(global::System.Int32 value);
        partial void OnOIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SKILL
        {
            get
            {
                return _SKILL;
            }
            set
            {
                OnSKILLChanging(value);
                ReportPropertyChanging("SKILL");
                _SKILL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SKILL");
                OnSKILLChanged();
            }
        }
        private global::System.String _SKILL;
        partial void OnSKILLChanging(global::System.String value);
        partial void OnSKILLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JRSS
        {
            get
            {
                return _JRSS;
            }
            set
            {
                OnJRSSChanging(value);
                ReportPropertyChanging("JRSS");
                _JRSS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JRSS");
                OnJRSSChanged();
            }
        }
        private Nullable<global::System.Int32> _JRSS;
        partial void OnJRSSChanging(Nullable<global::System.Int32> value);
        partial void OnJRSSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> INTERVIEWERRATING
        {
            get
            {
                return _INTERVIEWERRATING;
            }
            set
            {
                OnINTERVIEWERRATINGChanging(value);
                ReportPropertyChanging("INTERVIEWERRATING");
                _INTERVIEWERRATING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("INTERVIEWERRATING");
                OnINTERVIEWERRATINGChanged();
            }
        }
        private Nullable<global::System.Int32> _INTERVIEWERRATING;
        partial void OnINTERVIEWERRATINGChanging(Nullable<global::System.Int32> value);
        partial void OnINTERVIEWERRATINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IID
        {
            get
            {
                return _IID;
            }
            set
            {
                OnIIDChanging(value);
                ReportPropertyChanging("IID");
                _IID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IID");
                OnIIDChanged();
            }
        }
        private Nullable<global::System.Int32> _IID;
        partial void OnIIDChanging(Nullable<global::System.Int32> value);
        partial void OnIIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__CANDIDATE_D__OID__276EDEB3", "CANDIDATE_DETAILS")]
        public EntityCollection<CANDIDATE_DETAILS> CANDIDATE_DETAILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CANDIDATE_DETAILS>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "CANDIDATE_DETAILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CANDIDATE_DETAILS>("RegFormAngularNodeModel.FK__CANDIDATE_D__OID__276EDEB3", "CANDIDATE_DETAILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALSKI__IID__24927208", "INTERVIEWER")]
        public INTERVIEWER INTERVIEWER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "INTERVIEWER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "INTERVIEWER").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<INTERVIEWER> INTERVIEWERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "INTERVIEWER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<INTERVIEWER>("RegFormAngularNodeModel.FK__OPTIONALSKI__IID__24927208", "INTERVIEWER", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALS__INTER__239E4DCF", "Rating")]
        public Rating Rating
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "Rating").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "Rating").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rating> RatingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "Rating", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALSK__JRSS__22AA2996", "Rating")]
        public Rating Rating1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "Rating").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "Rating").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rating> Rating1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "Rating");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rating>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "Rating", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RegFormAngularNodeModel", Name="Rating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rating object.
        /// </summary>
        /// <param name="rID">Initial value of the RID property.</param>
        public static Rating CreateRating(global::System.Int32 rID)
        {
            Rating rating = new Rating();
            rating.RID = rID;
            return rating;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RID
        {
            get
            {
                return _RID;
            }
            set
            {
                if (_RID != value)
                {
                    OnRIDChanging(value);
                    ReportPropertyChanging("RID");
                    _RID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RID");
                    OnRIDChanged();
                }
            }
        }
        private global::System.Int32 _RID;
        partial void OnRIDChanging(global::System.Int32 value);
        partial void OnRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORY__INTER__1CF15040", "MANDATORYSKILS")]
        public EntityCollection<MANDATORYSKIL> MANDATORYSKILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "MANDATORYSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORY__INTER__1CF15040", "MANDATORYSKILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__MANDATORYS__JRSS__1BFD2C07", "MANDATORYSKILS")]
        public EntityCollection<MANDATORYSKIL> MANDATORYSKILS1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "MANDATORYSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MANDATORYSKIL>("RegFormAngularNodeModel.FK__MANDATORYS__JRSS__1BFD2C07", "MANDATORYSKILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALS__INTER__239E4DCF", "OPTIONALSKILS")]
        public EntityCollection<OPTIONALSKIL> OPTIONALSKILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "OPTIONALSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALS__INTER__239E4DCF", "OPTIONALSKILS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RegFormAngularNodeModel", "FK__OPTIONALSK__JRSS__22AA2996", "OPTIONALSKILS")]
        public EntityCollection<OPTIONALSKIL> OPTIONALSKILS1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "OPTIONALSKILS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OPTIONALSKIL>("RegFormAngularNodeModel.FK__OPTIONALSK__JRSS__22AA2996", "OPTIONALSKILS", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
